---
title: "Code Profiling Assignment"
author: "Amaan, Alex, Patrick, Peter"
date: "04/20/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

PROFVIS CODE PROFILE

```{r}
# load data:
df <- EBMAforecast::presidentialForecast

#load profvis package
library(profvis)

profvis({
# PRELIMINARY 1: Number of models:
K <- dim(df)[2] - 1

# PRELIMINARY 2: Number of observations:
Ti <- dim(df)[1]

# PRELIMINARY 3: Create function that combines steps (2) & (3):
steps23 <- function(df = df, w_hat = wHat_it[i-1,]){
  y <- df[[7]] # Create vector of outcome variables.
  M <- df[,1:K] # create matrix of models.
  K <- dim(df)[2] - 1 # Number of models.
  Ti <- dim(df)[1] #Number of observations
  # Create dnorm object for step 2:
  dnormal <- t(
    sapply(
      X = 1:Ti,
      FUN = function(t){
        dnorm(
          y[t],
          sapply(
            X = 1:K,
            FUN = function(k){df[t,k]}
            ),
          sd = 1
          )
        }
      )
    )
  # Do step 2 function:
  z_hats <- t(
    sapply(
      X = 1:Ti,
      FUN = function(t){
        (w_hat * dnormal[t,])/(sum(w_hat * dnormal[t,]))
        }
      )
    )
  # Do step 3 function:
  w_hat2 <- sapply(
    X = 1:K,
    FUN = function(k){
      sum(z_hats[,k])/Ti
    }
  )
  return(w_hat2)
}

# PRELIMINARY 4: create matrix to collect iterations data. It needs to have 21 rows for the initial w_hat and the 20 iterations of w_hat.
itnum <- 20 # Number of iterations
wHat_it <- matrix(
  data = NA,
  nrow = itnum + 1,
  ncol = K
  )
colnames(wHat_it) <- c("Campbell",
                       "Lewis-Beck",
                       "EWT2C2",
                       "Fair",
                       "Hibbs",
                       "Abramowitz"
                       )
rownames(wHat_it) <- 0:itnum

# STEP 1: Define w_hat with all models weighted equally.
wHat_it[1,] <- replicate(K,1/K)

# Steps 2-4 (ITERATION):
i <- 2 
while(i <= itnum + 1){
  wHat_it[i,] <- steps23(df = df, w_hat = wHat_it[i-1,])
  print(i)
  i = i + 1
}

# FINAL ITERATION:
wHat_it[tail(itnum,1),]
})
```



